### ISSUE TITLE
compatibility when keras uses tf backend

### ISSUE THREAD

**Issue by joemzhao** [williamleif/socialsent#15]
Hi William,

First of all thanks for the great work and codes!

I meet a compatibility problem using the **densifier**  part and managed to fix it. It might be good to verify with you to see if it's a general case, thanks!

in `example.py`, I tried to directly call **densifier** by

`densify(embeddings, pos_seeds, neg_seeds)`

then following raises

`  File "/mounts/Users/student/mzhao/mytools/temp/socialsent/socialsent/embedding_transformer.py", line 146, in <lambda>
    model.add_node(Lambda(lambda x: K.reshape(K.sqrt(K.sum(x * x, axis=1)), (x.shape[0], 1))),
  File "/mounts/Users/student/mzhao/env/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 271, in reshape
    return tf.reshape(x, shape)
  File "/mounts/Users/student/mzhao/env/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "/mounts/Users/student/mzhao/env/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
TypeError: Expected binary or unicode string, got Dimension(None)`

which is essentially raised from 

https://github.com/williamleif/socialsent/blob/master/socialsent/embedding_transformer.py#L146

when try to get tensor shape, and could be easily fixed by `K.shape(x)[0]` 

I am wondering if you meet this problem?

My environment:
Keras==0.3.3
tensorflow==1.8.0 & tensorflow==1.0.0 (no gpu)
OS: openSUSE Leap 15.0

Thanks!

**Comment by jyayoub** [comment]
hi Joe, 
I am trying to use densifier in the same way as you did but I keep on receiving this error: 
TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(None), 1). Consider casting elements to a supported type.
Exception TypeError: "'NoneType' object is not callable" in <bound method BoolGauge.__del__ of <tensorflow.python.eager.monitoring.BoolGauge object at 0x7f7c88e4dcd0>> ignored
Do you have any suggestions?

**Comment by joemzhao** [comment]
> hi Joe,
> I am trying to use densifier in the same way as you did but I keep on receiving this error:
> TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(None), 1). Consider casting elements to a supported type.
> Exception TypeError: "'NoneType' object is not callable" in <bound method BoolGauge.**del** of <tensorflow.python.eager.monitoring.BoolGauge object at 0x7f7c88e4dcd0>> ignored
> Do you have any suggestions?

hi @jyayoub,

it's a bit non-trivial to go through these codes due to different and legacy keras/tf versions. I write a numpy-based densifier seems also working: 

https://github.com/joemzhao/ultradensifier

hope it could be helpful to you.

**Comment by jyayoub** [comment]
Hi Joe,
Sorry for bothering you again.
I was able to run Williams code using the random walk method and I
outputted a list of words with polarities. But I wanted to try the
densifier method so I can compare both outputs, so do you have any
instructions on how to do that with the code that you have provided to me?
I am have my dataset and  a word embedding .
I would appreciate your help.
Thank you!
